# Generated by Django 2.2.7 on 2019-12-07 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumSessionTable',
            fields=[
                ('site', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numSession', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='SiteMedianTable',
            fields=[
                ('site', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('median', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueSiteTable',
            fields=[
                ('visitor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_of_unique_sites', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
